//
// Created by ghita on 25/04/2021.
//

#ifndef PROJET_THEORIE_DES_GRAPHES_STATION_DE_SKI_G_ALLEGRO_H
#define PROJET_THEORIE_DES_GRAPHES_STATION_DE_SKI_G_ALLEGRO_H

#include "Station.h"


int affichageInterface();

#endif //PROJET_THEORIE_DES_GRAPHES_STATION_DE_SKI_G_ALLEGRO_H
